//----generated by ot_top_mod.py------ 
//---- ot_top declare OT_SRAM start------ 
wire cen_otsr_0 ,cen_otsr_1 ; 
wire wen_otsr_0 ,wen_otsr_1 ; 
wire [ 10 -1 : 0 ] addr_otsr_0 ,addr_otsr_1 ; 
wire [ 64 -1 : 0 ] din_otsr_0 ,din_otsr_1 ; 
wire [ 64 -1 : 0 ] dout_otsr_0 ,dout_otsr_1 ; 
//---- ot top declare OT_SRAM end------ 

//----declare ot_top sram write signal start------ 
wire osw_cen_otsr_0 ; 
wire osw_wen_otsr_0 ; 
wire [ 10 -1 : 0 ] osw_addr_otsr_0 ; 
wire [ 64 -1 : 0 ] osw_din_otsr_0 ; 
//----declare ot_top sram write signal  end------ 
//----generated by ot_top_mod.py------ 
//----instance OT_SRAM start------ 
OT_SRAM otbf_0(.Q(	dout_otsr_0 ),	.CLK( clk ),.CEN( cen_otsr_0 ),.WEN( wen_otsr_0 ),.A( addr_otsr_0 ),.D( din_otsr_0 ),.EMA( 3'b0 ));//----instance OT SRAM_0---------
OT_SRAM otbf_1(.Q(	dout_otsr_1 ),	.CLK( clk ),.CEN( cen_otsr_1 ),.WEN( wen_otsr_1 ),.A( addr_otsr_1 ),.D( din_otsr_1 ),.EMA( 3'b0 ));//----instance OT SRAM_1---------
//----instance OT_SRAM end------ 
